version: '3.2'
services:
  php-eastlearning:
    # need this for dev environments and proper debugging
    volumes:
      - type: bind
        source: .
        target: /app
    build: .
    stdin_open: true
    tty: true
    env_file:
      - local.env
    ports:
      - "8000:8000"
    networks:
      vpcbr:
        ipv4_address: 10.11.0.2

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.11.0.0/16






